# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", inline: <<-SHELL
    /vagrant/prepareMaster.sh
  SHELL

  # one vagrantfile must only use one image.
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "master" do |master|
      $hostName = "master"
      config.vm.hostname = $hostName
      config.vm.network :private_network, ip: "10.141.141.10"
  end

#  config.vm.define "slave1" do |slave1|
#    config.vm.box = "playa_mesos_ubuntu_14.04"
#    config.vm.network :private_network, ip: "10.141.141.11"
#  end


end
