# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    $master1_IP="10.141.141.10"
    $master1_hostName="master1"

    $slave1_IP="10.141.141.11"
    $slave1_hostName="slave1"

    # one vagrantfile must only use one image.
    config.vm.box = "ubuntu/trusty64"

    config.vm.define $master1_hostName  do |master1|
        config.vm.provision "shell", inline: "bash /vagrant/prepareMaster.sh " + $master1_IP
        config.vm.hostname = $master1_hostName
        config.vm.network :private_network, ip: $master1_IP
    end

    config.vm.define $slave1_hostName do |slave1|
        config.vm.provision "shell", inline: "bash /vagrant/prepareMaster.sh " + $slave1_IP
        config.vm.hostname = $slave1_hostName
        config.vm.network :private_network, ip: $slave1_IP
    end
end
